"""
PDF compliance report generator using fpdf2.
Produces a downloadable, professional-looking report.
"""

from fpdf import FPDF
from datetime import datetime
import io


class ComplianceReport(FPDF):
    """Custom FPDF subclass with header/footer branding."""

    def __init__(self, city: str):
        super().__init__()
        self.city = city

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 60, 114)
        self.cell(0, 12, "CitySync AI", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 11)
        self.set_text_color(80, 80, 80)
        self.cell(0, 7, "Building Plan Compliance Report", new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by CitySync AI", align="C")


def generate_compliance_pdf(results: list[dict], city: str,
                             compliance_score: float,
                             total_area: float) -> bytes:
    """
    Generates a PDF compliance report.

    Args:
        results: List of compliance result dicts from the rule engine.
        city: City name used for the rule set.
        compliance_score: Overall compliance percentage.
        total_area: Total computed area in sq ft.

    Returns:
        bytes: The PDF file content.
    """
    pdf = ComplianceReport(city=city)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    def clean(val) -> str:
        if val is None:
            return ""
        s = str(val)
        return s.replace("•", "-").replace("—", "-").replace("–", "-").replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'").encode('latin-1', 'replace').decode('latin-1')


    # ── Meta info ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 6, f"City: {city}  |  Date: {ts}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Summary metrics ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)

    pass_count = sum(1 for r in results if r["status"] == "PASS")
    fail_count = sum(1 for r in results if r["status"] == "FAIL")

    pdf.cell(0, 6, f"Total Area: {total_area:.1f} sq ft", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Total Rooms Verified: {len(results)}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Compliance Score: {compliance_score:.1f}%", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Passed: {pass_count}  |  Failed: {fail_count}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Results table ────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Room-by-Room Results", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table header
    col_widths = [40, 22, 22, 22, 22, 62]
    headers = ["Room", "Area", "Req.", "Width", "Status", "Reason"]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(30, 60, 114)
    pdf.set_text_color(255, 255, 255)
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1, fill=True, align="C")
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 8)
    for row in results:
        status = row["status"]
        if status == "PASS":
            pdf.set_fill_color(212, 237, 218)
            pdf.set_text_color(21, 87, 36)
        elif status == "FAIL":
            pdf.set_fill_color(248, 215, 218)
            pdf.set_text_color(114, 28, 36)
        elif status == "INSUFFICIENT_DATA":
            pdf.set_fill_color(255, 243, 205)
            pdf.set_text_color(133, 100, 4)
        else:
            pdf.set_fill_color(240, 240, 240)
            pdf.set_text_color(60, 60, 60)

        req = str(row["required_area_sqft"]) if row["required_area_sqft"] else "N/A"
        eff_width = f"{min(row['width_ft'], row['length_ft']):.1f}" if row["width_ft"] and row["length_ft"] else "N/A"

        pdf.cell(col_widths[0], 7, clean(row["room_name"])[:20], border=1, fill=True)
        pdf.cell(col_widths[1], 7, f"{row['area_sqft']:.0f}", border=1, fill=True, align="C")
        pdf.cell(col_widths[2], 7, req, border=1, fill=True, align="C")
        pdf.cell(col_widths[3], 7, eff_width, border=1, fill=True, align="C")
        pdf.cell(col_widths[4], 7, status, border=1, fill=True, align="C")
        pdf.cell(col_widths[5], 7, clean(row["reason"])[:35], border=1, fill=True)
        pdf.ln()

    # ── Fix Suggestions ──────────────────────────────────────────────
    failing = [r for r in results if r.get("suggested_fix")]
    if failing:
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Suggested Fixes", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        for r in failing:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"{clean(r['room_name'])}:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, f"  {clean(r['suggested_fix'])}")
            pdf.ln(1)

    # ── Code References ──────────────────────────────────────────────
    refs = [r for r in results if r.get("code_reference")]
    if refs:
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Regulation References", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(80, 80, 80)
        seen = set()
        for r in refs:
            ref = clean(r["code_reference"])
            if ref not in seen:
                seen.add(ref)
                pdf.multi_cell(0, 5, f"- {ref}")
                pdf.ln(1)

    # ── Disclaimer ───────────────────────────────────────────────────
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 4,
        "Disclaimer: This report is generated by CitySync AI for preliminary compliance assessment only. "
        "It does not constitute legal or engineering certification. All results must be verified by a "
        "licensed architect or municipal authority before submission."
    )

    return bytes(pdf.output())
